#!/usr/bin/env python3
"""Submit the prepared Vennek proof fixture to Cardano preprod.

Requires:
- ~/.config/vennek/vennek.env with BLOCKFROST_PROJECT_ID for preprod
- ~/.config/vennek/preprod-wallet.json generated by /tmp/create_preprod_wallet.py
- samples/proof-fixtures/vennek-proof-fixture.json

This script does not print secrets or mnemonics.
"""
from pathlib import Path
import json
import os
import re
import time

from pycardano import (
    Address,
    AlonzoMetadata,
    AuxiliaryData,
    BlockFrostChainContext,
    ExtendedSigningKey,
    HDWallet,
    Metadata,
    Network,
    TransactionBuilder,
)

ROOT = Path('/mnt/Projects/elly_code/vennek')
ENV = Path('/home/son/.config/vennek/vennek.env')
WALLET = Path('/home/son/.config/vennek/preprod-wallet.json')
ADDR_FILE = Path('/home/son/.config/vennek/preprod-address.txt')
FIXTURE = ROOT / 'samples/proof-fixtures/vennek-proof-fixture.json'


def load_env(path: Path):
    for line in path.read_text().splitlines():
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key, value)


def save_env_value(key: str, value: str):
    text = ENV.read_text()
    if re.search(rf'^{re.escape(key)}=.*$', text, re.M):
        text = re.sub(rf'^{re.escape(key)}=.*$', f'{key}={value}', text, flags=re.M)
    else:
        text += ('\n' if text and not text.endswith('\n') else '') + f'{key}={value}\n'
    ENV.write_text(text)
    ENV.chmod(0o600)


def keys_and_address():
    mnemonic = json.loads(WALLET.read_text())['mnemonic']
    hd = HDWallet.from_mnemonic(mnemonic)
    payment = ExtendedSigningKey.from_hdwallet(hd.derive_from_path("m/1852'/1815'/0'/0/0"))
    stake = ExtendedSigningKey.from_hdwallet(hd.derive_from_path("m/1852'/1815'/0'/2/0"))
    address = Address(payment.to_verification_key().hash(), stake.to_verification_key().hash(), Network.TESTNET)
    ADDR_FILE.write_text(str(address) + '\n')
    ADDR_FILE.chmod(0o600)
    return payment, stake, address


def main():
    load_env(ENV)
    if os.environ.get('BLOCKFROST_NETWORK') != 'preprod':
        raise SystemExit('BLOCKFROST_NETWORK must be preprod for this script.')
    project_id = os.environ.get('BLOCKFROST_PROJECT_ID', '').strip()
    if not project_id:
        raise SystemExit('BLOCKFROST_PROJECT_ID is required.')

    payment, stake, address = keys_and_address()
    fixture = json.loads(FIXTURE.read_text())
    payload = dict(fixture['receipt']['payload'])
    # Cardano metadata text strings are limited to 64 bytes. The local proof
    # command uses a URI-style `sha256:<hex>` value (71 bytes), so the on-chain
    # fixture stores the 64-byte hex digest and uses the same value as the
    # integration-test expected content hash.
    content_hash = str(payload['content_hash'])
    if content_hash.startswith('sha256:'):
        content_hash = content_hash.removeprefix('sha256:')
        payload['content_hash'] = content_hash

    context = BlockFrostChainContext(project_id, network=Network.TESTNET)
    utxos = context.utxos(str(address))
    if not utxos:
        print('NO_UTXO: fund this preprod address first')
        print(str(address))
        return 2

    builder = TransactionBuilder(context)
    builder.add_input_address(address)
    builder.auxiliary_data = AuxiliaryData(AlonzoMetadata(metadata=Metadata({674: payload})))
    signed = builder.build_and_sign([payment, stake], change_address=address)
    tx_id = str(signed.id)
    context.submit_tx(signed)
    save_env_value('BLOCKFROST_TEST_TX_HASH', tx_id)
    save_env_value('BLOCKFROST_TEST_CONTENT_HASH', content_hash)
    print('SUBMITTED tx_hash=' + tx_id)
    print('content_hash=' + content_hash)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
